name = "homegame-wellknown"
main = "cf/worker.mjs"
compatibility_date = "2025-09-24"
workers_dev = true

routes = [
  { pattern = "homegame.today/*", zone_name = "homegame.today" },
  { pattern = "*.homegame.today/*", zone_name = "homegame.today" },
]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
